
// This file has been generated by the GUI designer. Do not modify.
namespace SQLiteBrowser
{
	public partial class NewTableDialog
	{
		private global::Gtk.VBox small_vbox;

		private global::Gtk.HBox table_row;

		private global::Gtk.Label TableNameLabel;

		private global::Gtk.Entry TableNameEntry;

		private global::Gtk.ScrolledWindow scrolled_columns;

		private global::Gtk.Table column_table;

		private global::Gtk.Button add_column;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SQLiteBrowser.NewTableDialog
			this.Name = "SQLiteBrowser.NewTableDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("Create New Table");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child SQLiteBrowser.NewTableDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "root_vbox";
			w1.BorderWidth = ((uint)(2));
			// Container child root_vbox.Gtk.Box+BoxChild
			this.small_vbox = new global::Gtk.VBox();
			this.small_vbox.Name = "small_vbox";
			this.small_vbox.Spacing = 6;
			// Container child small_vbox.Gtk.Box+BoxChild
			this.table_row = new global::Gtk.HBox();
			this.table_row.Name = "table_row";
			this.table_row.Spacing = 6;
			// Container child table_row.Gtk.Box+BoxChild
			this.TableNameLabel = new global::Gtk.Label();
			this.TableNameLabel.Name = "TableNameLabel";
			this.TableNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Table Name");
			this.table_row.Add(this.TableNameLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.table_row[this.TableNameLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child table_row.Gtk.Box+BoxChild
			this.TableNameEntry = new global::Gtk.Entry();
			this.TableNameEntry.CanFocus = true;
			this.TableNameEntry.Name = "TableNameEntry";
			this.TableNameEntry.IsEditable = true;
			this.TableNameEntry.InvisibleChar = '•';
			this.table_row.Add(this.TableNameEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.table_row[this.TableNameEntry]));
			w3.Position = 1;
			this.small_vbox.Add(this.table_row);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.small_vbox[this.table_row]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child small_vbox.Gtk.Box+BoxChild
			this.scrolled_columns = new global::Gtk.ScrolledWindow();
			this.scrolled_columns.CanFocus = true;
			this.scrolled_columns.Name = "scrolled_columns";
			this.scrolled_columns.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolled_columns.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.column_table = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.column_table.Name = "column_table";
			this.column_table.RowSpacing = ((uint)(6));
			this.column_table.ColumnSpacing = ((uint)(6));
			w5.Add(this.column_table);
			this.scrolled_columns.Add(w5);
			this.small_vbox.Add(this.scrolled_columns);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.small_vbox[this.scrolled_columns]));
			w8.Position = 1;
			// Container child small_vbox.Gtk.Box+BoxChild
			this.add_column = new global::Gtk.Button();
			this.add_column.CanFocus = true;
			this.add_column.Name = "add_column";
			this.add_column.UseUnderline = true;
			this.add_column.Label = global::Mono.Unix.Catalog.GetString("_Add Column");
			global::Gtk.Image w9 = new global::Gtk.Image();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
			this.add_column.Image = w9;
			this.small_vbox.Add(this.add_column);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.small_vbox[this.add_column]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			w1.Add(this.small_vbox);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1[this.small_vbox]));
			w11.Position = 0;
			// Internal child SQLiteBrowser.NewTableDialog.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonCancel]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString("_Create");
			w12.Add(this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonOk]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.add_column.Clicked += new global::System.EventHandler(this.AddColumnRow);
			this.buttonOk.Clicked += new global::System.EventHandler(this.CreateClicked);
		}
	}
}
