
// This file has been generated by the GUI designer. Do not modify.
namespace SQLiteBrowser
{
	public partial class ColumnRow
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry ColumnNameEntry;

		private global::Gtk.ComboBox DataTypeCombo;

		private global::Gtk.Button DeleteColumnButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SQLiteBrowser.ColumnRow
			global::Stetic.BinContainer.Attach(this);
			this.Name = "SQLiteBrowser.ColumnRow";
			// Container child SQLiteBrowser.ColumnRow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ColumnNameEntry = new global::Gtk.Entry();
			this.ColumnNameEntry.CanFocus = true;
			this.ColumnNameEntry.Name = "ColumnNameEntry";
			this.ColumnNameEntry.IsEditable = true;
			this.ColumnNameEntry.InvisibleChar = '•';
			this.hbox1.Add(this.ColumnNameEntry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ColumnNameEntry]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.DataTypeCombo = global::Gtk.ComboBox.NewText();
			this.DataTypeCombo.Name = "DataTypeCombo";
			this.hbox1.Add(this.DataTypeCombo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.DataTypeCombo]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.DeleteColumnButton = new global::Gtk.Button();
			this.DeleteColumnButton.CanFocus = true;
			this.DeleteColumnButton.Name = "DeleteColumnButton";
			this.DeleteColumnButton.UseStock = true;
			this.DeleteColumnButton.UseUnderline = true;
			this.DeleteColumnButton.Label = "gtk-delete";
			this.hbox1.Add(this.DeleteColumnButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.DeleteColumnButton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
